name: Deploy to Cloud Run

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: MasterKeys # This matches the Environment you configured

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Decode and save Firebase service account key
        run: echo "${{ secrets.GCLOUD_SERVICE_KEY }}" > firebase-service-account.json

      - name: Build Docker image
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/jobseek-backend/jobseek-backend .

      - name: Push Docker image
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
          docker push us-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/jobseek-backend/jobseek-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image us-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/jobseek-backend/jobseek-backend \
            --region ${{ secrets.CLOUD_RUN_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars PORT=8080,JWT_SECRET=${{ secrets.JWT_SECRET }},JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Cleanup
        run: rm -f firebase-service-account.json
